### ISSUE TITLE
The model conversion succeeded, but the .kmodel file could not be found

### ISSUE THREAD

**Issue by lzt1203** [kendryte/nncase#1012]
Fatal: Value cannot be null.
Parameter name: path1
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at NnCase.Converter.K210.Converters.GraphToK210Converter.ConvertAsync(Dataset dataset, GraphPlanContext planContext, String outputDir, String prefix, Boolean channelwiseOutput) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\GraphToK210Converter.cs:line 46
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 271
   at NnCase.Cli.Program.<Main>(String[] args)

The model conversion succeeded, but the .kmodel file could not be found

**Comment by curioyang** [comment]
k210 need nncase version <= 1.9
