### ISSUE TITLE
双输入onnx模型，编译kmodel的时候报错

### ISSUE THREAD

**Issue by gong-flying** [kendryte/nncase#1056]
**Describe the bug**
双输入onnx模型，编译kmodel的时候报错
**（compile_options.preprocess = True）报错信息如下：**
```python
 Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Nncase.IR.InvalidType' to type 'Nncase.IR.TensorType'.)
 ---> System.InvalidCastException: Unable to cast object of type 'Nncase.IR.InvalidType' to type 'Nncase.IR.TensorType'.
   at Nncase.CostModel.EGraphOpCostEvaluateContext.GetReturnType[T]()
   at Nncase.Evaluator.NN.Conv2DEvaluator.Visit(ICostEvaluateContext context, Conv2D target)
   at Nncase.Evaluator.ICostEvaluator`1.Nncase.Evaluator.ICostEvaluator.Visit(ICostEvaluateContext context, Op target)
   at Nncase.Evaluator.CostEvaluateProvider.EvaluateOpCost(Op op, ICostEvaluateContext context)
   at Nncase.CompilerServicesProvider.EvaluateOpCost(Op op, ICostEvaluateContext context)
   at Nncase.CompilerServices.EvaluateOpCost(Op op, ICostEvaluateContext context)
   at Nncase.CostModel.EGraphCostEvaluator.<>c__DisplayClass22_0.<Visit>b__0(Cost[] costs)
   at Nncase.CostModel.EGraphCostEvaluator.Visit(ENode enode, Func`2 costGetter)
   at Nncase.CostModel.EGraphCostEvaluator.Visit(ENode enode, Call call, IRType returnType)
   at Nncase.CostModel.EGraphCostEvaluator.Visit(ENode enode, IRType returnType)
   at Nncase.CostModel.EGraphCostEvaluator.Visit(EClass eclass)
   at Nncase.CostModel.EGraphCostEvaluator.TryEvaluateAll()
   at Nncase.CostModel.EGraphCostEvaluator.Evaluate()
   at Nncase.Passes.EGraphExtractExtensions.Extract(IEGraph eGraph, EClass root, IBaseFuncCostEvaluator basefunc_cost_evaluator)
   at Nncase.Passes.EGraphExtractPass.RunCoreAsync(IEGraph input, RunPassContext context)
   at Nncase.Passes.Pass`2.RunAsync(TInput input, RunPassContext context)
   at Nncase.Passes.PassManager.FunctionPassGroup.Runner.RunAsync()
   at Nncase.Passes.PassManager.FunctionPassGroup.RunAsync(IRModule module)
   at Nncase.Passes.PassManager.RunAsync(IRModule module)
   at Nncase.Compiler.Compiler.RunPassAsync(Action`1 register, String name)
   at Nncase.Compiler.Compiler.CompileAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nncase.Compiler.Interop.CApi.CompilerCompile(IntPtr compilerHandle)
Aborted (core dumped)
```
**（compile_options.preprocess = False）报错信息如下：**
```python
Nncase.IR.Call -> slice: 6, layer: 4
dim2-> start: 0, end: 160, dim3-> start: 0, end: 320
dim2-> start: 0, end: 160, dim3-> start: 320, end: 640
dim2-> start: 160, end: 320, dim3-> start: 0, end: 320
dim2-> start: 160, end: 320, dim3-> start: 320, end: 640
dim2-> start: 320, end: 480, dim3-> start: 0, end: 320
dim2-> start: 320, end: 480, dim3-> start: 320, end: 640
Unhandled exception. System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values. (Parameter '[Error] in ccr clr, ccr id:3'))
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter '[Error] in ccr clr, ccr id:3')
   at Nncase.Passes.Rules.K230.Ccr.Clear()
   at Nncase.Passes.Rules.K230.CcrHandler.ClearItems(List`1 ccrsToClr)
   at Nncase.Passes.Rules.K230.GnneActionUpdater.UpdateCcr(List`1 ccrsToSet, List`1 ccrsToClr)
   at Nncase.Passes.Rules.K230.GnneActionUpdater.UpdateMfuAct1InFuse(SegmentND l2RPsum, SegmentND l2RIf2, SegmentND ifmap2, SegmentND l2GOf, SegmentND ofmap, ACT1_SOURCE_TYPE sourceType1, ACT1_SOURCE_TYPE sourceType2, DataType quantType1, DataType quantType2, DataType quantTypeD, DeQuantizeParam deqParams1, DeQuantizeParam deqParams2, Int32 rshiftBits1, Int32 rshiftBits2, Int32 rshiftBitsD, Boolean is16Segments, Int32 ofPp, Int32 l1Pp, List`1 l2RIf2CcrsToClr, List`1 ofCcrsToSet, List`1 ofCcrsToClr, Int32 offsetSSrc2, Int32 offsetAct1, Int32 offsetOfmap, ItemName src2ItemName, List`1 act1CcrsToClr, MFU_ACT1_FUNCTION actType)
   at Nncase.Passes.Rules.K230.GnneActionUpdater.UpdateL2RPsum(Call dw, Call pool, Call act1, SegmentND l2RIf2, SegmentND ifmap2, SegmentND l2RDw, SegmentND l2RPsum, SegmentND l2GOf, SegmentND storeOf, Int32 ofPp, Int32 l1Pp, ACT0_OUTPUT_DEST destTarget, TcuComputeMode tcuMode, Int32 ocPerGroup, WeightGroupHandler weightGroup, List`1 l2RIf2CcrsToClr, List`1 ofCcrsToSet, List`1 ofCcrsToClr, Int32 offsetSSrc2, Int32 offsetAct, Int32 offsetAct1, Int32 offsetOfmap, Int32 offsetSDw, Int32 offsetSDwQarg, ItemName src2ItemName, List`1 dwCcrsToClr, List`1 act1CcrsToClr, Boolean swapAB)
   at Nncase.Passes.Rules.K230.TileConv2D.BuildL1Schedule(GnneActionUpdater actionUpdater, TiledGlb glb, SegmentND ifmap, SegmentND weight, SegmentND psum, Int32 iPp, Int32 ofPp, Int32 wPp, SegmentND ifmap2, Boolean weightGroupOnly, WeightGroupHandler weightGroup, Int32& l1Pp, PhysicalBuffer ddrW)
   at Nncase.Passes.Rules.K230.TileConv2D.BuildIfFirstSchedule(TiledGlb glb, Call convCall, Call ld, Call st, PhysicalBuffer ddrIf, PhysicalBuffer ddrOf, PhysicalBuffer ddrW, PhysicalBuffer ddrWQarg, PhysicalBuffer ddrAct, PhysicalBuffer ddrDW, PhysicalBuffer ddrDWQarg, PhysicalBuffer ddrDWAct, PhysicalBuffer ddrAct1, PhysicalBuffer ddrPdpAct, PhysicalBuffer ddrIf2, Boolean weightGroupOnly, WeightGroupHandler weightGroup)
   at Nncase.Passes.Rules.K230.TileConv2D.GetReplace(Call call, Call ld, Call st, Fusion fusion)
   at Nncase.Passes.Rules.K230.TileConv2D.GetReplace(IMatchResult __result, RunPassContext __context)
   at Nncase.Passes.Rules.Tile.L1FusionChecker.Convert()
   at Nncase.Passes.Rules.Tile.CheckedConvertMutator.RewriteLeafFusion(Fusion expr)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitTuple(Tuple expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitCall(Call expr, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.VisitOperands(Expr expr, TContext context)
   at Nncase.IR.ExprVisitor`3.VisitFunction(Function expr, TContext context)
   at Nncase.IR.Function.Accept[TExprResult,TTypeResult,TContext](ExprFunctor`3 functor, TContext context)
   at Nncase.IR.ExprVisitor`3.DispatchVisit(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter`1.Rewrite(Expr expr, TContext context)
   at Nncase.IR.ExprRewriter.Rewrite(Expr expr)
   at Nncase.Passes.Rules.Tile.K230FusionToTirPass.RunCoreAsync(IRModule module, RunPassContext options)
   at Nncase.Passes.Pass`2.RunAsync(TInput input, RunPassContext context)
   at Nncase.Passes.PassManager.ModulePassGroup.RunAsync(IRModule module)
   at Nncase.Passes.PassManager.RunAsync(IRModule module)
   at Nncase.Compiler.Compiler.RunPassAsync(Action`1 register, String name)
   at Nncase.Compiler.Compiler.CompileAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nncase.Compiler.Interop.CApi.CompilerCompile(IntPtr compilerHandle)
Aborted (core dumped)
```

**To Reproduce**
```python
python3 ./scripts/seafusion_onnx.py --target k230 --model models/seafusion.onnx
```
**Expected behavior**
通过nncase编译onnx模型成功生成kmodel模型。

**Origin model and code**
编译脚本seafusion_onnx.py内容如下：
```python
import os
import argparse
import numpy as np
from PIL import Image
import onnxsim
import onnx
import nncase

def parse_model_input_output(model_file):
    onnx_model = onnx.load(model_file)
    input_all = [node.name for node in onnx_model.graph.input]
    input_initializer = [node.name for node in onnx_model.graph.initializer]
    input_names = list(set(input_all) - set(input_initializer))
    input_tensors = [
        node for node in onnx_model.graph.input if node.name in input_names]

    print("input_tensors:",input_tensors)
    # input
    inputs = []
    for _, e in enumerate(input_tensors):
        onnx_type = e.type.tensor_type
        input_dict = {}
        input_dict['name'] = e.name
        input_dict['dtype'] = onnx.mapping.TENSOR_TYPE_TO_NP_TYPE[onnx_type.elem_type]
        input_dict['shape'] = [(i.dim_value if i.dim_value != 0 else d) for i, d in zip(
            onnx_type.shape.dim, [1, 1, 480, 640])]
        inputs.append(input_dict)

        print("inputs:",inputs)

    return onnx_model, inputs


def onnx_simplify(model_file, dump_dir):
    onnx_model, inputs = parse_model_input_output(model_file)
    onnx_model = onnx.shape_inference.infer_shapes(onnx_model)
    input_shapes = {}
    for input in inputs:
        input_shapes[input['name']] = input['shape']

    onnx_model, check = onnxsim.simplify(onnx_model, input_shapes=input_shapes)
    assert check, "Simplified ONNX model could not be validated"

    model_file = os.path.join(dump_dir, 'simplified.onnx')
    onnx.save_model(onnx_model, model_file)
    return model_file


def read_model_file(model_file):
    with open(model_file, 'rb') as f:
        model_content = f.read()
    return model_content

def generate_data_ramdom(shape, batch):
    calib_data = []
    #calib_data = [[np.random.rand(1, 480, 640).astype(np.float32)],[np.random.rand(1, 480, 640).astype(np.float32)]]
    calib_data = [[np.random.rand(1, 1, 480, 640).astype(np.float32)],[np.random.rand(1, 1, 480, 640).astype(np.float32)]]
    #print("calib_data", calib_data)
    return calib_data

def generate_data(shape, batch, vis_dir, ir_dir):
    vis_img_paths = [os.path.join(vis_dir, p) for p in os.listdir(vis_dir)]
    ir_img_paths = [os.path.join(ir_dir, p) for p in os.listdir(ir_dir)]
    data = []
    for i in range(batch):
        assert i < len(vis_img_paths), "vis images not enough."
        vis_data = Image.open(vis_img_paths[i]).convert('RGB')
        vis_data = vis_data.resize((shape[3], shape[2]), Image.BILINEAR)
        vis_data = np.asarray(vis_data, dtype=np.float32)
        vis_data = np.transpose(vis_data, (2, 0, 1))
        data.append([vis_data[np.newaxis, ...]])

        assert i < len(ir_img_paths), "ir images not enough."
        ir_data = Image.open(vis_img_paths[i]).convert('L')
        ir_data = ir_data.resize((shape[3], shape[2]), Image.BILINEAR)
        ir_data = np.asarray(ir_data, dtype=np.float32)
        ir_data = np.transpose(ir_data, (2, 0, 1))
        data.append([ir_data[np.newaxis, ...]])

    return data

def main():
    parser = argparse.ArgumentParser(prog="nncase")
    parser.add_argument("--target", type=str, help='target to run')
    parser.add_argument("--model", type=str, help='model file')
    #parser.add_argument("--vis", type=str, help='visible_dataset')
    #parser.add_argument("--ir", type=str, help='infrared_dataset')

    args = parser.parse_args()

    input_shape = [1, 1, 480, 640]

    dump_dir = 'tmp/sea_fusion'
    if not os.path.exists(dump_dir):
        os.makedirs(dump_dir)

    # onnx simplify
    model_file = onnx_simplify(args.model, dump_dir)

    # compile_options
    compile_options = nncase.CompileOptions()
    compile_options.target = args.target
    compile_options.preprocess = True
    compile_options.swapRB = True
    compile_options.input_shape = input_shape
    compile_options.input_type = 'float32'
    compile_options.input_range = [0, 1]
    compile_options.mean = [0, 0, 0]
    compile_options.std = [1, 1, 1]
    compile_options.input_layout = 'NCHW'
    compile_options.output_layout = 'NCHW'
    compile_options.dump_ir = True
    compile_options.dump_asm = True
    compile_options.dump_dir = dump_dir

    # compiler
    compiler = nncase.Compiler(compile_options)

    # import
    model_content = read_model_file(model_file)
    import_options = nncase.ImportOptions()
    compiler.import_onnx(model_content, import_options)

    # ptq_options
    ptq_options = nncase.PTQTensorOptions()
    ptq_options.samples_count = 1
    #ptq_options.set_tensor_data({generate_data(input_shape, ptq_options.samples_count, args.vis),generate_data(input_shape, ptq_options.samples_count, args.ir)})
    #ptq_options.set_tensor_data(generate_data(input_shape, ptq_options.samples_count).tobytes())
    #ptq_options.set_tensor_data(generate_data(input_shape, ptq_options.samples_count, args.vis, args.ir))
    ptq_options.set_tensor_data(generate_data_ramdom(input_shape, ptq_options.samples_count))
    compiler.use_ptq(ptq_options)

    # compile
    compiler.compile()

    # kmodel
    kmodel = compiler.gencode_tobytes()
    with open(os.path.join(dump_dir, 'model_seafusion.kmodel'), 'wb') as f:
        f.write(kmodel)

if __name__ == '__main__':
    main()
```

**Environment (please complete the following information):**
 - OS: ubuntu-20.04
 -nncase Version: 2.2.0.20230728
 - nncase版本信息

>>> import _nncase
>>> print(_nncase.__version__)
2.2.0-fb83c3a

onnx模型文件
[model_seafusion.zip](https://github.com/kendryte/nncase/files/12356151/model_seafusion.zip)

**Comment by curioyang** [comment]
@gong-flying 
`preprocess == True` 因为你的输入是单通道，mean std也要给成单channel的。

脚本中校正集设置有点问题，多输入需要按照[[x1,x2,x3...],[y1,y2,y3...]]，如下:
```
calib_data = [[],[]]
for i in range(size):
    calib_data[0].append(xxx)
    calib_data[1].append(xxx)
```
其它问题目前还在解决中

**Comment by gong-flying** [comment]
> 
脚本中校正集我这边参考sdk中k230_sdk/src/big/nncase/examples/user_guide/k230_simulate.ipynb文件multiple inputs进行设置的。如果按照你说的设置，目前会报如下错误：
```python
Traceback (most recent call last):
  File "./scripts/seafusion_onnx.py", line 194, in <module>
    main()
  File "./scripts/seafusion_onnx.py", line 182, in main
    ptq_options.set_tensor_data(generate_data_ramdom(input_shape, ptq_options.samples_count))
  File "/usr/local/lib/python3.8/dist-packages/nncase/__init__.py", line 91, in set_tensor_data
    self.cali_data = [RuntimeTensor.from_numpy(
  File "/usr/local/lib/python3.8/dist-packages/nncase/__init__.py", line 91, in <listcomp>
    self.cali_data = [RuntimeTensor.from_numpy(
TypeError: from_numpy(): incompatible function arguments. The following argument types are supported:
    1. (arg0: numpy.ndarray) -> _nncase.RuntimeTensor

Invoked with: [array([[[[0.56988937, 0.7042464 , 0.33550593, ..., 0.08011147,
          0.17793241, 0.3784576 ],
         [0.59596694, 0.7835871 , 0.16781692, ..., 0.86008745,
          0.5161125 , 0.8696202 ],
         [0.9346573 , 0.7052592 , 0.9758041 , ..., 0.30026066,
          0.99670464, 0.63064027],
         ...,
         [0.2541594 , 0.54538846, 0.70382446, ..., 0.45342252,
          0.94604915, 0.764474  ],
         [0.22703631, 0.9196133 , 0.9815477 , ..., 0.48613974,
          0.68930435, 0.05582329],
         [0.5498387 , 0.58120954, 0.24636427, ..., 0.40910494,
          0.8104795 , 0.36752528]]]], dtype=float32)]
```

**Comment by gong-flying** [comment]
您好：




按照您说的方式设置校正集：
defgenerate_data_ramdom(shape, batch):
    #calib_data = []
    #calib_data = [[np.random.rand(1, 480, 640).astype(np.float32)],[np.random.rand(1, 480, 640).astype(np.float32)]]
    #calib_data = [[np.random.rand(1, 1, 480, 640).astype(np.float32)],[np.random.rand(1, 1, 480, 640).astype(np.float32)]]
    calib_data = [[],[]]
    for i inrange(batch):
        calib_data[0].append([np.random.rand(1, 1, 480, 640).astype(np.float32)])
        calib_data[1].append([np.random.rand(1, 1, 480, 640).astype(np.float32)])
    print("calib_data", calib_data)
    return calib_data


目前编译时会报错，报错信息：
Traceback (mostrecentcalllast):
  File"./scripts/seafusion_onnx.py", line194, in<module>main()
  File"./scripts/seafusion_onnx.py", line182, inmainptq_options.set_tensor_data(generate_data_ramdom(input_shape, ptq_options.samples_count))
  File"/usr/local/lib/python3.8/dist-packages/nncase/__init__.py", line91, inset_tensor_dataself.cali_data= [RuntimeTensor.from_numpy(
  File"/usr/local/lib/python3.8/dist-packages/nncase/__init__.py", line91, in<listcomp>self.cali_data= [RuntimeTensor.from_numpy(
TypeError: from_numpy(): incompatiblefunctionarguments. Thefollowingargumenttypesaresupported:
    1. (arg0: numpy.ndarray) ->_nncase.RuntimeTensorInvokedwith: [array([[[[0.56988937, 0.7042464 , 0.33550593, ..., 0.08011147,
          0.17793241, 0.3784576 ],
         [0.59596694, 0.7835871 , 0.16781692, ..., 0.86008745,
          0.5161125 , 0.8696202 ],
         [0.9346573 , 0.7052592 , 0.9758041 , ..., 0.30026066,
          0.99670464, 0.63064027],
         ...,
         [0.2541594 , 0.54538846, 0.70382446, ..., 0.45342252,
          0.94604915, 0.764474  ],
         [0.22703631, 0.9196133 , 0.9815477 , ..., 0.48613974,
          0.68930435, 0.05582329],
         [0.5498387 , 0.58120954, 0.24636427, ..., 0.40910494,
          0.8104795 , 0.36752528]]]], dtype=float32)]
我原先的校正集时参考sdk中k230_sdk/src/big/nncase/examples/user_guide/k230_simulate.ipynb文件multiple inputs进行设置的





在 2023-08-17 15:21:58，"Curio Yang" ***@***.***> 写道：

@gong-flying
preprocess == True 因为你的输入是单通道，mean std也要给成单channel的。

脚本中校正集设置有点问题，多输入需要按照[[x1,x2,x3...],[y1,y2,y3...]]，如下:

calib_data = [[],[]]
for i in range(size):
    calib_data[0].append(xxx)
    calib_data[1].append(xxx)


其它问题目前还在解决中

**Comment by curioyang** [comment]
@gong-flying 你的代码中多了[]，相当于是 
```
[ [ [x1],[x2] ], [ [y1],[y2] ] ]
```
```
 for i inrange(batch):
        calib_data[0].append([np.random.rand(1, 1, 480, 640).astype(np.float32)])
        calib_data[1].append([np.random.rand(1, 1, 480, 640).astype(np.float32)])
```
应该是
```
[ [ x1,x2 ], [ y1,y2 ] ]
```
```
 for i inrange(batch):
        calib_data[0].append(np.random.rand(1, 1, 480, 640).astype(np.float32))
        calib_data[1].append(np.random.rand(1, 1, 480, 640).astype(np.float32))
```

**Comment by gong-flying** [comment]
> ```python
> def generate_data_ramdom(shape, batch):
>     calib_data = []
>     #calib_data = [[np.random.rand(1, 480, 640).astype(np.float32)],[np.random.rand(1, 480, 640).astype(np.float32)]]
>     calib_data = [[np.random.rand(1, 1, 480, 640).astype(np.float32)],[np.random.rand(1, 1, 480, 640).astype(np.float32)]]
>     #print("calib_data", calib_data)
>     return calib_data
> ```

1.那这种设置校正集与脚本中原有的设置应该没啥区别？
def generate_data_ramdom(shape, batch):
    calib_data = []
    #calib_data = [[np.random.rand(1, 480, 640).astype(np.float32)],[np.random.rand(1, 480, 640).astype(np.float32)]]
    calib_data = [[np.random.rand(1, 1, 480, 640).astype(np.float32)],[np.random.rand(1, 1, 480, 640).astype(np.float32)]]
    #print("calib_data", calib_data)
    return calib_data

2.mean 与std修改成单通道也是报同样的错误

3.请问下提到的报错是否能复现，是否我这边提供更多的信息来定位问题

**Comment by curioyang** [comment]
> 1.那这种设置校正集与脚本中原有的设置应该没啥区别？
> 
> > ```python
> > def generate_data_ramdom(shape, batch):
> >     calib_data = []
> >     #calib_data = [[np.random.rand(1, 480, 640).astype(np.float32)],[np.random.rand(1, 480, 640).astype(np.float32)]]
> >     calib_data = [[np.random.rand(1, 1, 480, 640).astype(np.float32)],[np.random.rand(1, 1, 480, 640).astype(np.float32)]]
> >     #print("calib_data", calib_data)
> >     return calib_data
> > ```
> 
> 2.mean 与std修改成单通道也是报同样的错误
> 
> 3.请问下提到的报错是否能复现，是否需要我这边提供更多的信息来定位问题

1. 是的，这个calib data 的格式是正确的
2. mean std 设置错误是引起 `(compile_options.preprocess = True）报错信息如下：`的原因
3. 问题可以复现，目前已经修复了，但是需要等28号的nncase-kpu新版本

**Comment by gong-flying** [comment]
> > 1.那这种设置校正集与脚本中原有的设置应该没啥区别？
> > > ```python
> > > def generate_data_ramdom(shape, batch):
> > >     calib_data = []
> > >     #calib_data = [[np.random.rand(1, 480, 640).astype(np.float32)],[np.random.rand(1, 480, 640).astype(np.float32)]]
> > >     calib_data = [[np.random.rand(1, 1, 480, 640).astype(np.float32)],[np.random.rand(1, 1, 480, 640).astype(np.float32)]]
> > >     #print("calib_data", calib_data)
> > >     return calib_data
> > > ```
> > 
> > 
> > 2.mean 与std修改成单通道也是报同样的错误
> > 3.请问下提到的报错是否能复现，是否需要我这边提供更多的信息来定位问题
> 
> 1. 是的，这个calib data 的格式是正确的
> 2. mean std 设置错误是引起 `(compile_options.preprocess = True）报错信息如下：`的原因
> 3. 问题可以复现，目前已经修复了，但是需要等28号的nncase-kpu新版本
 
您好，针对第二点我这边**mean std**设置单通道报错跟之前一致，请问一下**mean std**设置何值能规避`(compile_options.preprocess = True）报错？

**Comment by curioyang** [comment]
@gong-flying mean std按照我上面的代码配置成单通道的就行了，需要等28号的新版本nncase-kpu才能跑
