### ISSUE TITLE
ncc error while compiling .tflite model

### ISSUE THREAD

**Issue by KonyashovNikita** [kendryte/nncase#1165]
I train my model using TF lite(tflite_model_maker python library used with EfficientDet-Lite0). When I tried to compile my .tflite model to kmodel format via following command:

`./tflite2kmodel.sh ../neroQR/model.tflite`

But i have this issue:

```uasge: ./tflite2kmodel.sh xxx.tflite
Fatal: Layer 114 is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer 114 is not supported
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 63
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 113
   at NnCase.Cli.Program.<Main>(String[] args)
```
Can you help me to understand issue?

**Comment by sunnycase** [comment]
Please fill the issule template.
