### ISSUE TITLE
nncase on pc run_kmodel error

### ISSUE THREAD

**Issue by shenhuxi-pen** [kendryte/nncase#1247]
----------   compile    ----------
Simplify...
[ onnx done ]
Set options...
Compiling...
----------------end-----------------

---------start run kmodel---------
Load kmodel...
Traceback (most recent call last):
  File "c:/Users/Administrator/Desktop/yolov5-7.0/guanwangdennase.py", line 217, in <module>
    results = run_kmodel(kmodel_path, input_data)
  File "c:/Users/Administrator/Desktop/yolov5-7.0/guanwangdennase.py", line 99, in run_kmodel
    model_sim.load_model(f.read())
RuntimeError

nncase use nncase==2.8.3 nncase_kpu==2.8.3  best.onnx =nncase2.8.3/examples/test.onx

**Comment by PermissionDenied7335** [comment]
不是，至少要把你的编译脚本内容放出来才有可能找得到问题吧
