### ISSUE TITLE
Is Flatten Layer not supported?

### ISSUE THREAD

**Issue by shanejohnpaul** [kendryte/nncase#175]
I tried the following network,

```
inputs = tf.keras.Input(shape=(40,40,3))
x = tf.keras.layers.Flatten()(inputs)
outputs = tf.keras.layers.Dense(10)(x)
model = tf.keras.Model(inputs, outputs)
```

```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_6 (InputLayer)         [(None, 40, 40, 3)]       0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 4800)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 10)                48010     
=================================================================
Total params: 48,010
Trainable params: 48,010
Non-trainable params: 0
_________________________________________________________________
```

With nncase v0.2.0-beta2, it says import graph, and then it ends with no errors and no kmodel.

With nncase v0.1.0-rc5, I get the following,
```
Fatal: Nullable object must have a value.
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertReshape(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 199
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 97
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 113
   at NnCase.Cli.Program.<Main>(String[] args)
```

I've attached the model here.
[model.zip](https://github.com/kendryte/nncase/files/5307443/model.zip)

I'm using TF2.x

**Comment by shanejohnpaul** [comment]
Update:
I just tried it with TensorFlow v2.0.0 and it finally works. I guess the latest version of TensorFlow (v2.3.0) is not well supported.
