### ISSUE TITLE
Fatal: input-format

### ISSUE THREAD

**Issue by chenhu66** [kendryte/nncase#18]
ncc.exe -i k210model -o inference --dataset ./images ./lenet2.kmodel ./output

Fatal: input-format
System.ArgumentException: input-format at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 117
at NnCase.Cli.Program.<Main>(String[] args)

**Comment by sunnycase** [comment]
inference mode is only supported in nighly-build.
You can download the nighly-build from https://ci.appveyor.com/project/sunnycase/nncase/branch/master/artifacts

**Comment by chenhu66** [comment]
i tried out the nightly-build, and now i got:

Fatal: Layer Quantize is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer Quantize is not supported
   at NnCase.Converter.K210.Emulator.K210Emulator.Run(Tensor`1 batch, K210Conv2dLayerArgument inputArgument) in C:\projects\nncase\src\NnCase.Converter.K210\Emulator\K210Emulator.cs:line 106
   at NnCase.Converter.K210.Emulator.K210Emulator.RunAsync(String datasetPath, String outputPath) in C:\projects\nncase\src\NnCase.Converter.K210\Emulator\K210Emulator.cs:line 59
   at NnCase.Converter.K210.Emulator.K210Emulator.RunAsync(String datasetPath, String outputPath) in C:\projects\nncase\src\NnCase.Converter.K210\Emulator\K210Emulator.cs:line 55
   at NnCase.Cli.Program.Main(String[] args) in C:\projects\nncase\src\NnCase.Cli\Program.cs:line 279
   at NnCase.Cli.Program.<Main>(String[] args)
