### ISSUE TITLE
Layer SUB is not supported

### ISSUE THREAD

**Issue by kimchicanh** [kendryte/nncase#19]
Hi,
I convert tflite to kmodel with command:
./ncc/ncc -i tflite -o k210model --dataset images $1 ./$name

this is error:

uasge: ./tflite2kmodel.sh xxx.tflite
Fatal: Layer SUB is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer SUB is not supported
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 63
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 110
   at NnCase.Cli.Program.<Main>(String[] args)

thanks

**Comment by kimchicanh** [comment]
If I use add with (- number) it will have this problem:
uasge: ./tflite2kmodel.sh xxx.tflite
Fatal: Index was outside the bounds of the array.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NnCase.Converter.Converters.TfLiteExtensions.ToNCHW(Int32[] shape) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 435
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertAdd(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 234
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 77
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 110
   at NnCase.Cli.Program.<Main>(String[] args)

**Comment by sunnycase** [comment]
nncase doesn't support broadcast a scalar now.

**Comment by kimchicanh** [comment]
@sunnycase 
So how can I sub a scalar
please help me
thanks

**Comment by sunnycase** [comment]
You can use BiasAdd.

**Comment by sunnycase** [comment]
This feature will be available in the next release.

**Comment by sunnycase** [comment]
You can try the newest nncase now.
