### ISSUE TITLE
Converting onnx model to kmodel

### ISSUE THREAD

**Issue by AMZzee** [kendryte/nncase#195]
I am getting an error, while converting an onnx model to kmodel. Not sure why, but i am guessing its because of the input shape of the model. 

cmd: 
./ncc/ncc /content/lightweight-human-pose-estimation.pytorch/human-pose-estimation.onnx modelpose.kmodel -i onnx -o kmodel -t k210

error: 
Fatal: Specified argument was out of the range of valid values.
Parameter name: value
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: value
   at CommandLine.Text.HelpText.AddLine(StringBuilder builder, String value, Int32 maximumLength)
   at CommandLine.Text.HelpText.AddPreOptionsLine(String value, Int32 maximumLength)
   at CommandLine.Text.HelpText.AddPreOptionsLine(String value)
   at CommandLine.Text.HelpText.DefaultParsingErrorsHandler[T](ParserResult`1 parserResult, HelpText current)
   at CommandLine.Text.HelpText.<>c__DisplayClass39_0`1.<AutoBuild>b__2(HelpText current)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex, Int32 maxDisplayWidth)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Int32 maxDisplayWidth)
   at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__1(IEnumerable`1 _, TextWriter writer)
   at CSharpx.MaybeExtensions.Do[T1,T2](Maybe`1 maybe, Action`2 action)
   at CommandLine.Parser.<>c__DisplayClass17_0`1.<DisplayHelp>b__0(IEnumerable`1 errors)
   at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
   at CommandLine.Parser.DisplayHelp[T](ParserResult`1 parserResult, TextWriter helpWriter, Int32 maxDisplayWidth)
   at CommandLine.Parser.MakeParserResult[T](ParserResult`1 parserResult, ParserSettings settings)
   at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args)
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 84
   at NnCase.Cli.Program.<Main>(String[] args)

what changes do i have to make to the existing model, to make it suitable for converting to kmodel.

**Comment by sunnycase** [comment]
nncase 0.1 doesn't support onnx models.
