### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kimchicanh** [kendryte/nncase#21]
Hi,
I use mobilenet keras 0.5 and convert it to kmodel but I got error:

uasge: ./tflite2kmodel.sh xxx.tflite
Fatal: Invalid dataset.
System.ArgumentException: Invalid dataset.
   at NnCase.Converter.Data.Dataset..ctor(String path, IReadOnlyCollection`1 allowdExtensions, ReadOnlySpan`1 dimensions, Int32 batchSize, PostprocessMethods postprocessMethod, Nullable`1 mean, Nullable`1 std) in D:\Work\Repository\nncase\src\NnCase.Converter\Data\Dataset.cs:line 67
   at NnCase.Converter.Data.ImageDataset..ctor(String path, ReadOnlySpan`1 dimensions, Int32 batchSize, PreprocessMethods preprocessMethods, PostprocessMethods postprocessMethod, Nullable`1 mean, Nullable`1 std) in D:\Work\Repository\nncase\src\NnCase.Converter\Data\Dataset.cs:line 165
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 225
   at NnCase.Cli.Program.<Main>(String[] args)

Thanks

**Comment by kimchicanh** [comment]
You can check this model:
https://drive.google.com/open?id=1pqVAuQ9D4kptZGStNMR6vpXjS3h8j8kG

**Comment by kimchicanh** [comment]
You can check this model:
https://drive.google.com/open?id=1pqVAuQ9D4kptZGStNMR6vpXjS3h8j8kG

**Comment by kimchicanh** [comment]
You can check this model:
https://drive.google.com/open?id=1pqVAuQ9D4kptZGStNMR6vpXjS3h8j8kG

**Comment by sunnycase** [comment]
What is your dataset?

**Comment by sunnycase** [comment]
If you have any questions, please reopen.
