### ISSUE TITLE
Fatal: Layer Quantize is not supported

### ISSUE THREAD

**Issue by chenhu66** [kendryte/nncase#26]
i tried to do inference for mnist lenet using the night build:
nncase_night/ncc -i k210model -o inference --dataset ./images ./lenet2.kmodel ./output

I got this error:
Fatal: Layer Quantize is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer Quantize is not supported
   at NnCase.Converter.K210.Emulator.K210Emulator.Run(Tensor`1 batch, K210Conv2dLayerArgument inputArgument) in C:\projects\nncase\src\NnCase.Converter.K210\Emulator\K210Emulator.cs:line 106
   at NnCase.Converter.K210.Emulator.K210Emulator.RunAsync(String datasetPath, String outputPath) in C:\projects\nncase\src\NnCase.Converter.K210\Emulator\K210Emulator.cs:line 59
   at NnCase.Converter.K210.Emulator.K210Emulator.RunAsync(String datasetPath, String outputPath) in C:\projects\nncase\src\NnCase.Converter.K210\Emulator\K210Emulator.cs:line 55
   at NnCase.Cli.Program.Main(String[] args) in C:\projects\nncase\src\NnCase.Cli\Program.cs:line 304
   at NnCase.Cli.Program.<Main>(String[] args)

**Comment by sunnycase** [comment]
Sorry but not all of the operators are implemented in inference mode. We are continuously developing the full operators support in inference mode.

**Comment by chenhu66** [comment]
Lenet is the simplest cnn, and thus I thought you might already support it. Can I ask when it is expected to be supported? I really need it to do some testing. Thank you.

**Comment by sunnycase** [comment]
You can try the newest nightly-build now.

**Comment by chenhu66** [comment]
Thank uou. Yes, it ran to the end, feels good. Unfortunately, result is wrong.
The issue is: I need to rescale the image value to -1 and 1, before running the kmodel, but your inference mode reads images directly, and I have no chance to touch the image values. How to solve this issue?

**Comment by sunnycase** [comment]
You should specify `--postprocess n1to1` when generating the kmodel.

**Comment by zhen8838** [comment]
can't inference :
```sh
ncc -i k210model -o inference --dataset ./tmp ./yolo_05.kmodel ./output 
Fatal: Layer QuantizedResizeNearestNeighbor is not supported
```

**Comment by sunnycase** [comment]
You can try the newest nncase now.
