### ISSUE TITLE
Fatal: Layer tflite.Operator is not supported: Only scalar multiply is supported

### ISSUE THREAD

**Issue by chenhu66** [kendryte/nncase#28]
hu@hu-VirtualBox:~/ws$ nncase_night/ncc  -i tflite -o k210model  lenet01.tflite lenet01.kmodel
Fatal: Layer tflite.Operator is not supported: Only scalar multiply is supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer tflite.Operator is not supported: Only scalar multiply is supported
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertMul(Operator op) in C:\projects\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 243
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in C:\projects\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 79
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in C:\projects\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in C:\projects\nncase\src\NnCase.Cli\Program.cs:line 113
   at NnCase.Cli.Program.<Main>(String[] args)

**Comment by sunnycase** [comment]
This feature will be available in the next release.

**Comment by sunnycase** [comment]
You can try the newest nncase now.

**Comment by eraser3112** [comment]
I tried the same and got the same result.

So I used the latest version(v0.2.0) and others.
Only the latest version of “nnc” is downloaded and replaced with the existing “nnc”.
And used the same command. 

But does not work. It exprains the commend.
How should we move the latest version?

Teach me Please!
![無題](https://user-images.githubusercontent.com/53464329/71041526-a5332b00-216c-11ea-8599-50b94e91a26d.png)
