### ISSUE TITLE
caffe模型转换失败

### ISSUE THREAD

**Issue by MaxwellAlen** [kendryte/nncase#29]
liu@EAIU:~/ncc-linux-x86_64$ ncc -i caffe -o k210model --dataset ./images ./mobilenet_yolov3_lite_deploy_iter_3000.caffemodel ./1.kmodel
Fatal: Layer AnnotatedData is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer AnnotatedData is not supported
   at NnCase.Converter.Converters.CaffeToGraphConverter.ConvertLayer(LayerParameter layerParam) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\CaffeToGraphConverter.cs:line 47
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.CaffeToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\CaffeToGraphConverter.cs:line 29
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 97
   at NnCase.Cli.Program.<Main>(String[] args)

不支持数据读取层 怎么解决呢？ @sunnycase

**Comment by sunnycase** [comment]
Please save your .caffemodel with the **deploy** prototxt.

**Comment by sunnycase** [comment]
Closed as inactive.
