### ISSUE TITLE
KPU ran out of memory

### ISSUE THREAD

**Issue by gheesung** [kendryte/nncase#32]
While converting tflite to kmodel, I am encountering out of memory. I still have 2.6GB ram left. Any comment?

```
2019-08-03 00:41:10.769773: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
0: InputLayer -> 1x3x224x224
1: K210Conv2d 1x3x224x224 -> 1x24x112x112
2: K210Conv2d 1x24x112x112 -> 1x24x112x112
3: K210Conv2d 1x24x112x112 -> 1x16x112x112
4: K210Conv2d 1x16x112x112 -> 1x96x112x112
Fatal: KPU ran out of memory.
System.InvalidOperationException: KPU ran out of memory.
   at NnCase.Converter.K210.Converters.Stages.Inference.KPUMemoryAllocator.Allocate(UInt32 size) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\KPUMemoryAllocator.cs:line 28
   at NnCase.Converter.K210.Converters.Stages.Inference.InferenceContext.GetOrAllocateKPUMemory(OutputConnector output) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferenceContext.cs:line 40
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.AllocateInputMemoryDefault(Layer layer, OutputConnector input, InferenceContext context) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 123
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 50
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.<Infer>g__InferLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 41
   at NnCase.Converter.K210.Converters.Stages.Inference.InferExecutor.Infer(Graph graph, ConvertContext convertContext) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Inference\InferExecutor.cs:line 106
   at NnCase.Converter.K210.Converters.GraphToK210Converter.ConvertAsync(Dataset dataset, GraphPlanContext planContext, String outputDir, String prefix, Boolean channelwiseOutput) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\GraphToK210Converter.cs:line 41
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 271
   at NnCase.Cli.Program.<Main>(String[] args)```

**Comment by sunnycase** [comment]
K210 only have 2MB dedicated memory for KPU. It says "KPU ran out of memory" not your PC.

**Comment by gheesung** [comment]
Does that mean that during the conversion, ncc will check the size of the model? I am converting mobilenet v2 and it is supposed to be smaller than v1.

**Comment by sunnycase** [comment]
@gheesung Not the size of the model, but the size of the feature maps. The model will be loaded into the 6MB generic RAM, but KPU can only use 2MB dedicated RAM to save input , intermediate and output feature maps. You may try decresing the size of the input feature map or use more downsampling layers to decrease the size intermediate feature map.

**Comment by gheesung** [comment]
@sunnycase thanks for your tips. I have decreased the image to 160x160 and it is able to convert successfully.
