### ISSUE TITLE
I get the error Fatal: Invalid dataset

### ISSUE THREAD

**Issue by kaeruko** [kendryte/nncase#35]
I'm doing a tutorial on making this kmodel
https://bbs.sipeed.com/t/topic/682

When proceeding in this way, the error mentioned in the title occurred

```
# ./tflite2kmodel.sh /tf/work/Maix-Keras-workspace/mbnet/mbnet75.tflite
uasge: ./tflite2kmodel.sh xxx.tflite
Fatal: Invalid dataset.
System.ArgumentException: Invalid dataset.
   at NnCase.Converter.Data.Dataset..ctor(String path, IReadOnlyCollection`1 allowdExtensions, ReadOnlySpan`1 dimensions, Int32 batchSize, PostprocessMethods postprocessMethod, Nullable`1 mean, Nullable`1 std) in D:\Work\Repository\nncase\src\NnCase.Converter\Data\Dataset.cs:line 67
   at NnCase.Converter.Data.ImageDataset..ctor(String path, ReadOnlySpan`1 dimensions, Int32 batchSize, PreprocessMethods preprocessMethods, PostprocessMethods postprocessMethod, Nullable`1 mean, Nullable`1 std) in D:\Work\Repository\nncase\src\NnCase.Converter\Data\Dataset.cs:line 212
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 249
   at NnCase.Cli.Program.<Main>(String[] args)
```

I would be grateful if you could give me advice on what to check.

Below is the model I created

https://drive.google.com/file/d/1W2u1D2zJAmnrNlqFqWP6E6l9QxpvQJyY/view?usp=sharing

**Comment by sunnycase** [comment]
You should put some images for calibration.
PS: Your tutorial is not produced by Kendryte but Sipeed. You may contact Sipeed for more help.
