### ISSUE TITLE
` Fatal: Layer Conv2d is not supported ' error when converting facenet tflite model to k210model using ncc

### ISSUE THREAD

**Issue by kaeruko** [kendryte/nncase#52]
When converting the following facenet tflite model using ncc
I get the error `Layer Conv2d is not supported`.

[tfilite file]
https://github.com/kaeruko/facenet/blob/d63293406b542d139cc3f99a1694faec8a57ca92/facenet.tflite

Is Conv2d not supported?

```bash
$ ./ncc/ncc -i tflite -o k210model --dataset images/ ../facenet/facenet.tflite 
2019-11-06 05:45:39.370357: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Fatal: Layer Conv2d is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer Conv2d is not supported
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.Convert(Graph graph, QuantizationContext quantizationContext, Int32 weightsBits) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 60
   at NnCase.Converter.K210.Converters.GraphToK210Converter.ConvertAsync(Dataset dataset, GraphPlanContext planContext, String outputDir, String prefix, Boolean channelwiseOutput) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\GraphToK210Converter.cs:line 40
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 271
   at NnCase.Cli.Program.<Main>(String[] args)
```

**Comment by sunnycase** [comment]
Use latest nncase

**Comment by kaeruko** [comment]
thx
