### ISSUE TITLE
 About LSTM ONNX Model To KModel Error

### ISSUE THREAD

**Issue by XS30** [kendryte/nncase#535]
**Describe the bug**
您好，我们尝试使用nncase 1.4转换经过测试的LSTM  ONNX模型，我的数据维度是[1，1，556]，而不是示例中的[1,3,224,224]，但是多次尝试模型转换均出现如下错误。之前怀疑是ONNX模型出错，但经过测试表明ONNX模型能正确工作。希望能帮助我们，感谢。

**To Reproduce**
Command line or scripts to reproduce the behavior:
报错如下
Slice_24(Slice)[Slice]->Squeeze_25(Squeeze)[Bitcast] has shape mismatch: [1,1,100]->[1,18446744073709551615,100]

**Expected behavior**
A clear and concise description of what you expected to happen._
顺利完成模型转换

**Origin model and code**
If applicable, add orgin model and code to help explain your problem.
原始模型与代码见此附件
[Model&Code.zip](https://github.com/kendryte/nncase/files/8220223/Model.Code.zip)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu18.04]
 - nncase version [e.g. v1.0.0.dev24]
 - DL Framework [e.g. TensorFlow 2.5.0]

**Additional context**

1. Import graph...
Traceback (most recent call last):
  File "F:/ONNX2KModel.py", line 92, in <module>
    main()
  File "F:/ONNX2KModel.py", line 79, in main
    compiler.import_onnx(model_content, import_options)
RuntimeError: Shapes must be same: 
Slice_24(Slice)[Slice]->Squeeze_25(Squeeze)[Bitcast] has shape mismatch: [1,1,100]->[1,18446744073709551615,100]

**Comment by XS30** [comment]
我转换的ONNX模型有问题，已解决。
