### ISSUE TITLE
NNCASE - Fatal: KPU allocator cannot allocate more memory.

### ISSUE THREAD

**Issue by yashhema** [kendryte/nncase#61]
Hello,
I have one class and image size is 224 320.
I downloaded the latest nncase . But when i try to convert a tflite model to kmodel, it gives me above error. (But conversion and inference work if I use inference type float)
I am using mobilenet v2 . If I try to use - https://github.com/kendryte/nncase/tree/v0.1.0-rc5
Model is converted to KModel  (of size 3.6 MB) but get error during inference - Layer QuantizedAdd is not supported.
But with latest Beta version, get KPU allocator cannot allocate more memory .

**Comment by yashhema** [comment]
I am using mobilenet v2 . If I try to use - https://github.com/kendryte/nncase/tree/v0.1.0-rc5
Model is converted to KModel  (of size 3.6 MB) but get error during inference - Layer QuantizedAdd is not supported.
But with latest Beta version, get KPU allocator cannot allocate more memory . I have one class and image size is 224 320
regards

**Comment by sunnycase** [comment]
Can you attach your tflite?

**Comment by evanthomas** [comment]
I'm having the same issue with this model and latest bcc
https://github.com/matpalm/bnn/blob/master/model.py

```
/ncc compile bnn_graph.tflite ./bnn_graph.kmodel -i tflite -o kmodel --dataset-format image --dataset ../bees/beedata/ncc-images
```

[bnn_graph.tflite.gz](https://github.com/kendryte/nncase/files/3960768/bnn_graph.tflite.gz)

tflite attached.

**Comment by sunnycase** [comment]
@evanthomas Your feature maps are too large to run on KPU. KPU has only 2MB dedicated RAM to store feature maps.

**Comment by anhnguyen2345** [comment]
@sunnycase 
https://colab.research.google.com/github/AIWintermuteAI/aXeleRate/blob/master/resources/aXeleRate_pascal20_detector.ipynb#scrollTo=uruWpeGRf6Qi I run follow this. and I got .tflite then convert it bt nncase0.1.0RC5 to kmodel (V3). 
Fatal: Layer TensorflowReshape is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer TensorflowReshape is not supported
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.<Convert>g__ConvertLayer|0_6(Layer layer, <>c__DisplayClass0_0& ) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 51
   at NnCase.Converter.K210.Converters.Stages.Convert.Converter.Convert(Graph graph, QuantizationContext quantizationContext, Int32 weightsBits) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\Stages\Convert\Converter.cs:line 60
   at NnCase.Converter.K210.Converters.GraphToK210Converter.ConvertAsync(Dataset dataset, GraphPlanContext planContext, String outputDir, String prefix, Boolean channelwiseOutput) in D:\Work\Repository\nncase\src\NnCase.Converter.K210\Converters\GraphToK210Converter.cs:line 40
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 271
   at NnCase.Cli.Program.<Main>(String[] args)
How can I fix it ?
