### ISSUE TITLE
Unable to convert tflite to kmodel

### ISSUE THREAD

**Issue by adelinawong** [kendryte/nncase#821]
Faced this error: 
Fatal: Layer DEQUANTIZE is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer DEQUANTIZE is not supported
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 63
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 113
   at NnCase.Cli.Program.<Main>(String[] args)

How do I go about solving this issue? Thank you!

**Comment by curioyang** [comment]
@adelinawong Your model should not be quantized.  NNCASE only supports floating-point models.
`converter = TFLiteConverter.from_saved_model(saved_model_dir)`
`tflite_model = converter.convert()`
Do not add other optimize options.
