### ISSUE TITLE
Fatal: Layer RELU is not supported

### ISSUE THREAD

**Issue by fmanid** [kendryte/nncase#954]
Im trying to convert a tflite model to kmodel, previously im using CNN model NASNetMobile, but when im trying to convert the model it is say error like this : 
/content/Maix_Toolbox
Fatal: Layer RELU is not supported
NnCase.Converter.Converters.LayerNotSupportedException: Layer RELU is not supported
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 63
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 113
   at NnCase.Cli.Program.<Main>(String[] args)

The code : 
import shutil

test_dataset_dir = '/content/test'

if not os.path.isdir(test_dataset_dir):
  os.mkdir(test_dataset_dir)

for key, value in validation_data.class_indices.items():
  src_dir = os.path.join(dataset_root_dir, dataset_name, key)
  dest_dir = os.path.join(test_dataset_dir, key)

  if not os.path.isdir(dest_dir):
    os.mkdir(dest_dir)

  count = 0
  for item in os.listdir(src_dir):
    file_path = os.path.join(src_dir, item)

    if os.path.isfile(file_path):
      shutil.copy(file_path, dest_dir)

    count += 1

    if count == 10:
      break
%cd /content/Maix_Toolbox
!./ncc/ncc -i tflite -o k210model --dataset /content/test /content/model.tflite /content/model.kmodel

**Comment by sunnycase** [comment]
nncase 0.x is not supported anymore, please use latest release.
